In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel('./Ether Fraud Transaction case study-23-5-22.xlsx')
data.head()

FLAG  Avg _Min_Sent_txn  Avg _Min_Recv_txn  Time_Diff  Min value received  \
0     0              21.80               0.00      65.40          101.000000   
1     0            1073.76            1476.59   24563.10            0.216334   
2     0              13.57           10125.40  638755.18            0.010053   
3     0          163765.17               0.00  327530.33            0.002457   
4     0           22371.43           29004.65  596613.23            0.005441   

   Max value received   Min value sent  Max value sent  Total transactions  
0           101.000000        1.000000       84.176518                   4  
1             6.999559        0.000000        7.557834                  21  
2            20.000000        0.008583       19.999769                 126  
3             0.002457        0.000000        0.000508                   3  
4          1000.000000        0.000000     1000.000000                  25

In [3]:
#count the values in FLAG
data.FLAG.value_counts()

0    7661
1    2179
Name: FLAG, dtype: int64

In [4]:
data.info() # no missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9840 entries, 0 to 9839
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   FLAG                 9840 non-null   int64  
 1   Avg _Min_Sent_txn    9840 non-null   float64
 2   Avg _Min_Recv_txn    9840 non-null   float64
 3   Time_Diff            9840 non-null   float64
 4   Min value received   9840 non-null   float64
 5   Max value received   9840 non-null   float64
 6   Min value sent       9840 non-null   float64
 7   Max value sent       9840 non-null   float64
 8   Total transactions   9840 non-null   int64  
dtypes: float64(7), int64(2)
memory usage: 692.0 KB


In [5]:
x = data.iloc[:,1:]
y = data.FLAG

In [6]:
y

0       0
1       0
2       0
3       0
4       0
       ..
9835    0
9836    0
9837    0
9838    1
9839    0
Name: FLAG, Length: 9840, dtype: int64

## splitting data into train and test

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=10)
len(x_train),len(x_test),len(y_train),len(y_test)

(7872, 1968, 7872, 1968)

## Building the decision tree model

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
model = dt.fit(x_train,y_train)

Predicting the model on test data

In [9]:
y_predict = model.predict(x_test)
y_predict

array([0, 0, 1, ..., 0, 1, 1])

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [11]:
confusion_matrix(y_test,y_predict)

array([[1465,   88],
       [  93,  322]])

In [12]:
accuracy_score(y_test,y_predict)

0.9080284552845529

## Introducing SMOTE

In [13]:
#!pip install imblearn

In [14]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()

In [15]:
x_train_SMOTE,y_train_SMOTE = smote.fit_resample(x_train.astype('float'),y_train)


In [16]:
#comparision with counter
from collections import Counter

In [17]:
print("Before SMOTE:",Counter(y_train))
print("After SMOTE:",Counter(y_train_SMOTE))

Before SMOTE: Counter({0: 6108, 1: 1764})
After SMOTE: Counter({0: 6108, 1: 6108})


In [18]:
model = dt.fit(x_train_SMOTE,y_train_SMOTE)

Predicting the model on test data

In [23]:
y_test= model.predict(x_test)

In [24]:
y_test

array([0, 0, 1, ..., 0, 1, 1])

In [25]:
confusion_matrix(y_test,y_predict)

array([[1444,   48],
       [ 114,  362]])

In [26]:
accuracy_score(y_test,y_predict)

0.9176829268292683